### ISSUE TITLE
BKDR Hash is not unique for all values

### ISSUE THREAD

**Issue by burimshala-zz** [zenozeng/color-hash#30]
When trying to generate a hash for values '2018-06-14T17' and '2018-06-15T09' you get the same value.

BKDRHash("2018-06-14T17") //186058161349561
BKDRHash("2018-06-15T09") //186058161349561

**Comment by nearwood** [comment]
I also ran into collisions with:

`textColor.hex("deploy live") === textColor("deploy next")`

When playing around with it, I had more collisions, seemingly due to the string starting with `deploy`.

![image](https://user-images.githubusercontent.com/1929778/115403846-66731200-a1b2-11eb-9419-3a14e4483c31.png)

**Comment by nearwood** [comment]
Oh, I see #21 and #27 deal with that.

**Comment by zenozeng** [comment]
![0934A2B3-BA2D-49F6-84A5-36864056F391](https://user-images.githubusercontent.com/2544489/115422826-db386180-a22f-11eb-80df-9cb812ab5e71.jpeg)


@nearwood color-hash@v2.0.0 uses SHA256 as default hash function, you can try the latest demo here: https://zenozeng.github.io/color-hash/demo/
